### PR TITLE
Provide TLS support for listening endpoint

### PR DESCRIPTION
**Pull request by andreas-habel**
Hi @GreenRover ,

due to our internal demand, I'm going to add TLS support to the listening endpoint of the exporter.
Initial commit is ready, but especially tests, more documentation and adjustments of docker build is outstanding. 

So, this is **not yet ready to merge** - if you even want to include that into the official version - but still any feedback and annotations are appreciated.

### CODE REVIEW

**Comment by GreenRover** [comment]
Looks good for me!

We have the same issue but operate the exporter with openshift/kubernetes and leave the ssl termination be done by openshift.

But for standalone or pure docker operation makes this totally sense

**Comment by andreas-habel** [comment]
Yeah, our central installations are running on openshift and k8s as well, so we're using the ingress controller to handle TLS there. However in future we plan to rollout the broker as well as the prometheus exporter in a couple thousand decentralized locations, only running on local Docker/Podman. That's why we need native TLS support. 
Maybe I'm going to add at least Basic Auth authentication for the endpoint as well in future, we'll see...

As of now, I feel like the PR is complete. I did some testing with private certificates, extended the documentation, ...
Ready for review 😄

**Comment by GreenRover** [comment]
Is this pr ready to merge?

**Comment by andreas-habel** [comment]
Yes, if you have no other objections to the implementation - it's tested and ready to merge.

**Review by GreenRover — APPROVED** [review]

**Comment by GreenRover** [comment]
Do you like to add auth feature first or needs a release?

**Pull request merged**
